# Generated by Django 5.2.13 on 2026-04-24 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('number', models.CharField(max_length=10, unique=True)),
                ('origin', models.CharField(max_length=80)),
                ('destination', models.CharField(max_length=80)),
                ('departure', models.DateTimeField()),
                ('arrival', models.DateTimeField()),
                ('travel_class', models.CharField(choices=[('SL', 'Sleeper'), ('3A', 'AC 3-Tier'), ('2A', 'AC 2-Tier'), ('1A', 'AC First Class'), ('CC', 'Chair Car'), ('EC', 'Executive Chair Car')], default='SL', max_length=2)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('seats_available', models.PositiveIntegerField(default=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='trains/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('departure',),
            },
        ),
    ]
