# Generated by Django 5.2.13 on 2026-04-21 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(default='India', max_length=80)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='destinations/')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('duration_days', models.PositiveIntegerField(default=3)),
                ('duration_nights', models.PositiveIntegerField(default=2)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('includes', models.TextField(blank=True, help_text='One item per line (e.g. Hotel stay, Breakfast, Airport transfer)')),
                ('description', models.TextField(blank=True)),
                ('itinerary', models.TextField(blank=True, help_text='Day-wise itinerary. One day per line.')),
                ('image', models.ImageField(blank=True, null=True, upload_to='packages/')),
                ('is_featured', models.BooleanField(default=False)),
                ('slots_available', models.PositiveIntegerField(default=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packages', to='packages.destination')),
            ],
            options={
                'ordering': ('-is_featured', '-created_at'),
            },
        ),
    ]
