# Generated by Django 5.2.13 on 2026-04-21 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=80)),
                ('country', models.CharField(default='India', max_length=80)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('star_rating', models.PositiveSmallIntegerField(default=3)),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rooms_available', models.PositiveIntegerField(default=20)),
                ('amenities', models.CharField(blank=True, help_text='Comma-separated list (e.g. WiFi, Pool, Spa, Gym)', max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='hotels/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-star_rating', 'name'),
            },
        ),
    ]
