# Generated by Django 5.2.13 on 2026-04-24 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Toyota Innova Crysta', max_length=120)),
                ('brand', models.CharField(blank=True, max_length=80)),
                ('category', models.CharField(choices=[('economy', 'Economy'), ('compact', 'Compact'), ('sedan', 'Sedan'), ('suv', 'SUV'), ('luxury', 'Luxury'), ('van', 'Van / MPV')], default='sedan', max_length=20)),
                ('pickup_location', models.CharField(max_length=120)),
                ('drop_location', models.CharField(blank=True, max_length=120)),
                ('transmission', models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic')], default='manual', max_length=20)),
                ('fuel_type', models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('electric', 'Electric'), ('hybrid', 'Hybrid')], default='petrol', max_length=20)),
                ('seats', models.PositiveSmallIntegerField(default=5)),
                ('luggage_capacity', models.PositiveSmallIntegerField(default=2, help_text='Number of large bags')),
                ('air_conditioning', models.BooleanField(default=True)),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cars_available', models.PositiveIntegerField(default=10)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cars/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('category', 'price_per_day'),
            },
        ),
    ]
