# Generated by Django 5.2.13 on 2026-04-24 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=80)),
                ('country', models.CharField(default='India', max_length=80)),
                ('category', models.CharField(choices=[('landmark', 'Landmark'), ('museum', 'Museum'), ('park', 'Park / Nature'), ('theme', 'Theme Park'), ('tour', 'Guided Tour'), ('experience', 'Experience'), ('adventure', 'Adventure'), ('cruise', 'Cruise'), ('water', 'Water Activity')], default='experience', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('highlights', models.TextField(blank=True, help_text='One highlight per line (e.g. Skip-the-line entry, English audio guide)')),
                ('duration_hours', models.DecimalField(decimal_places=1, default=2, help_text='Estimated duration in hours', max_digits=4)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rating', models.DecimalField(decimal_places=1, default=4.5, help_text='0 - 5', max_digits=3)),
                ('reviews_count', models.PositiveIntegerField(default=0)),
                ('slots_available', models.PositiveIntegerField(default=50)),
                ('is_featured', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='attractions/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-is_featured', '-rating', 'name'),
            },
        ),
    ]
