# Generated by Django 5.2.13 on 2026-04-24 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flights', '0001_initial'),
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightHotelDeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Mumbai → Goa: 3N Beachfront Combo', max_length=150)),
                ('destination_city', models.CharField(max_length=80)),
                ('nights', models.PositiveIntegerField(default=3)),
                ('travelers', models.PositiveIntegerField(default=2)),
                ('combined_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('savings', models.DecimalField(decimal_places=2, default=0, help_text='Amount saved vs booking separately', max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('inclusions', models.TextField(blank=True, help_text='One inclusion per line (e.g. Round-trip flight, 3 nights hotel, Daily breakfast)')),
                ('is_featured', models.BooleanField(default=False)),
                ('slots_available', models.PositiveIntegerField(default=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='flighthotel/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('flight', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='combo_deals', to='flights.flight')),
                ('hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='combo_deals', to='hotels.hotel')),
            ],
            options={
                'ordering': ('-is_featured', '-created_at'),
            },
        ),
    ]
